GlyemiApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("doctor/", include("doctor.urls")),
    path("patient/", include("patient.urls")),
    path("", include("home.urls")),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import register_doctor, register_patient, login_user, logout_user

app_name = "accounts"

urlpatterns = [
    path('connexion_patient/', register_patient, name='connexion_patient'),
    path('connexion_doctor/', register_doctor, name='connexion_doctor'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),

]

doctor/urls.py
from django.urls import path
from .views import home, suivi, suivi_patient, MessageSendPatientsAndAllMessages, MessageSendDoctor

app_name = "doctor"

urlpatterns = [
    path("", home, name="home"),
    path("suivi/", suivi, name="suivi"),
    path("allPatientsMessages/", MessageSendPatientsAndAllMessages, name="allPatientsMessages"),
    path("suivi_patient/<int:id>/", suivi_patient, name="suivi_patient"),
    path("MessageSendPatients/<int:id>/", MessageSendPatientsAndAllMessages, name="MessageSendPatients"),
    path("MessageSendDoctor/<int:id>/", MessageSendDoctor, name="MessageSendDoctor"),
]

home/urls.py
from django.urls import path
from .views import index

app_name = "home"

urlpatterns = [
    path("", index, name="index"),
]

patient/urls.py
from django.urls import path
from .views import home, MessageDoctorAndAllMessages, consultation

app_name = "patient"

urlpatterns = [
    path("", home, name="home"),
    path("MessageDoctorAndAllMessages/", MessageDoctorAndAllMessages, name="MessageToDoctor"),
    path("MessageDoctorAndAllMessages/<int:id>", MessageDoctorAndAllMessages, name="MessageToDoctorAll"),
    path("consultation", consultation, name="consultation"),
]

templates/base.html
<!doctype html>
{% load static %}
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Medical </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">

	<!-- CSS here -->
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/gijgo.css' %}">

    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/animated-headline.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>
<body>
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'assets/img/logo/loder.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
<header>
    <!--? Header Start -->
    <div class="header-area">
        <div class="main-header header-sticky">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <!-- Logo -->
                    <div class="col-xl-2 col-lg-2 col-md-1">
                        <div class="logo">
                            <a href="/"><img src="{% static 'assets/img/logo/glycemi.png' %}" alt=""></a>
                        </div>
                    </div>
                    <div class="col-xl-10 col-lg-10 col-md-10">
                        <div class="menu-main d-flex align-items-center justify-content-end">
                            <!-- Main-menu -->
                            <div class="main-menu f-right d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a href="/">ACCEUIL</a></li>
                                        <li><a href="about.html">A PROPOS</a></li>
                                        <li><a href="{% url 'accounts:connexion_doctor' %}">DOCTEURS</a></li>
                                        <li><a href="department.html">SERVICES</a></li>
                                    </ul>
                                </nav>
                            </div>
                            <div class="header-right-btn f-right d-none d-lg-block ml-30">
                                <a href="{% url 'accounts:connexion_patient' %}" class="btn header-btn">se connecter</a>
                            </div>
                    </div>   
                    <!-- Mobile Menu -->
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
</header>


{% block content %}

{% endblock content %}

    <footer>
        <!--? Footer Start-->
        <div class="footer-area section-bg" data-background="assets/img/gallery/footer_bg.jpg">
            <div class="container">
                <div class="footer-top footer-padding">
                    <div class="row d-flex justify-content-between">
                        <div class="col-xl-3 col-lg-3 col-md-4 col-sm-8">
                            <div class="single-footer-caption mb-50">
                                <!-- logo -->
                                <div class="footer-logo">
                                    <a href="index.html"><img src="{% static 'assets/img/logo/glycemi.png' %}" alt=""></a>
                                </div>
                            </div>
                        </div>

                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-8">
                            <div class="single-footer-caption mb-50">
                                <div class="footer-number mb-50">
                                    <h4><span>+243  </span>975 988 800</h4>
                                    <p>mktegra@gmail.com</p>
                                </div>
                                <!-- Form -->
                                <div class="footer-form">
                                    <div id="mc_embed_signup">
                                        <form method="get" class="subscribe_form relative mail_part" novalidate="true">
                                            <input type="email" name="EMAIL" id="newsletter-form-email" placeholder="  Adresse Email " class="placeholder hide-on-focus" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your email address'">
                                            <div class="form-icon">
                                                <button type="submit" name="submit" id="newsletter-submit" class="email_icon newsletter-submit button-contactForm">
                                                    Envoyer
                                                </button>
                                            </div>
                                            <div class="mt-10 info"></div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer-bottom">
                    <div class="row d-flex justify-content-between align-items-center">
                        
                        <div class="col-xl-3 col-lg-4">
                            <!-- Footer Social -->
                            <div class="footer-social f-right">
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="https://www.facebook.com/sai4ull"><i class="fab fa-facebook-f"></i></a>
                                <a href="#"><i class="fab fa-whatsapp"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>
    <!-- Scroll Up -->
    <div id="back-top" >
        <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
    </div>

    <!-- JS here -->

    <script src="{% static 'assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static 'assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/slick.min.js' %}"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="{% static 'assets/js/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/animated.headline.js' %}"></script>
    <script src="{% static 'assets/js/jquery.magnific-popup.js' %}"></script>

    <!-- Date Picker -->
    <script src="{% static 'assets/js/gijgo.min.js' %}"></script>
    <!-- Nice-select, sticky -->
    <script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.sticky.js' %}"></script>
    
    <!-- counter , waypoint -->
    <script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'assets/js/waypoints.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.countdown.min.js' %}"></script>
    <!-- contact js -->
    <script src="{% static 'assets/js/contact.js' %}"></script>
    <script src="{% static 'assets/js/jquery.form.js' %}"></script>
    <script src="{% static 'assets/js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'assets/js/mail-script.js' %}"></script>
    <script src="{% static 'assets/js/jquery.ajaxchimp.min.js' %}"></script>
    
    <!-- Jquery Plugins, main Jquery -->	
    <script src="{% static 'assets/js/plugins.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    
    </body>
</html>

templates/base_doctor.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/bootstrap/css_bootstrap.css' %}">
  <script src="{% static 'css/bootstrap/bootstrap.js' %}" defer></script>

  <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
  
  <!-- my css and js -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="{% static 'js/main.js' %}" defer></script>
  <script src="{% static 'js/chart.js' %}"></script>
  <title>
    {% block title %}

    {% endblock %}
  </title>
</head>
<body>

  <header id="header" class="header">

    <div class="top_top__bar">
      <div class="topbar d-flex align-items-center container">
        <div class="connexion-welcome">
          <p>
            Bienvenue Docteur 
            {% if user.is_authenticated and user.isDoctor %}
              {{ user.username }}
            {% endif %}
          </p>
          <p><a href="{% url 'accounts:logout' %}">Se Déconnecter</a></p>
        </div>

        <div class="message-notification">
          <p><a href="{% url 'doctor:allPatientsMessages' %}"><i class="fa-solid fa-message"></i></a></p>
          <span>
            {% block message %}
            
            {% endblock %}
          </span>
        </div>
        <div class="message-notification">
          <p><a href="#"><i class="fa-solid fa-bell"></i></a></p>
          <span>0</span>
        </div>
      </div>
    </div>

    <div class="branding d-flex align-items-center sticky-top">

      <div class="container position-relative d-flex align-items-center justify-content-between ">

        <a href="/doctor/" class="logo d-flex align-items-center me-auto">
          <img src="{% static 'images/logo.png' %}" alt="logo">
        </a>

        <nav id="navmenu" class="navmenu">
          <ul>
            <li><a href="/doctor/" class="active">Accueil<br></a></li>
            <li><a href="{% url 'doctor:suivi' %}">Suivis</a></li>
          </ul>
        </nav>
      </div>
    </div>

  </header>

  {% block content %}
  {% endblock %}

</body>
</html>

templates/base_patient.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/bootstrap/css_bootstrap.css' %}">
  <script src="{% static 'css/bootstrap/bootstrap.js' %}" defer></script>

  <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
  
  <!-- my css and js -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="{% static 'js/main.js' %}" defer></script>
  <script src="{% static 'js/chart.js' %}"></script>
  <title>
    {% block title %}

    {% endblock %}
  </title>
</head>
<body>

  <header id="header" class="header sticky-top">

    <div class="top_top__bar">
      <div class="topbar d-flex align-items-center container">
        <div class="connexion-welcome">
          <p>
            Bienvenue  
            {% if user.is_authenticated and user.isPatient %}
              {{ user.username }}
            {% endif %}
          </p>
          <p><a href="{% url 'accounts:logout' %}">Se Déconnecter</a></p>
        </div>

        <div class="message-notification">
          <p><a href="{% url 'patient:MessageToDoctor' %}"><i class="fa-solid fa-message"></i></a></p>
          <span>
            {% block message %}
            
            {% endblock %}
          </span>
        </div>
        <div class="message-notification">
          <p><a href="#"><i class="fa-solid fa-bell"></i></a></p>
          <span>0</span>
        </div>
      </div>
    </div>

    <div class="branding d-flex align-items-center">
      <div class="container position-relative d-flex align-items-center justify-content-between">

        <a href="/patient/" class="logo d-flex align-items-center me-auto">
          <img src="{% static 'images/logo.png' %}" alt="logo">
        </a>

        <nav id="navmenu" class="navmenu">
          <ul>
            <li><a href="/patient/" class="active">Accueil<br></a></li>
            <li><a href="{% url 'patient:consultation'  %}">Consultation</a></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>

  {% block content %}
  {% endblock %}

</body>
</html>